FIX MEV Boost
dappnode/DAppNodePackage-teku pull request #58
Opened 2023-04-04 23:07 UTC by alexpeterson91

add a new MEV-boost Param to resolve MEV-Boost issue 
fixes #57

2023-04-05 09:09 UTC, dsimog01 requested changes
If the package is published like this and someone installs it having that same flag in EXTRA_OPTS, it will probably break the package

2023-04-14 09:51 UTC, dsimog01 approved these changes

2023-04-14 09:53 UTC, pablomendezroyo approved these changes

2023-04-14 09:55 UTC, dsimog01 approved these changes

2023-04-14 09:59 UTC, dsimog01 approved these changes

2023-04-14 09:59 UTC, merged